# Generated by Django 4.0.4 on 2022-06-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(default='Anonymous', max_length=20)),
                ('product_image', models.ImageField(default='', upload_to='home/images')),
                ('Price', models.IntegerField(default=0)),
                ('Description', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
