# Generated by Django 4.0.4 on 2022-06-14 07:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_pub_date_alter_product_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=254)),
                ('password', models.CharField(default='', max_length=40)),
                ('phone', models.IntegerField(default='', max_length=11)),
                ('adress', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=40)),
                ('city', models.CharField(default='', max_length=40)),
                ('pincode', models.IntegerField(default='', max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Product_name',
            new_name='product_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Pub_date',
        ),
        migrations.AddField(
            model_name='product',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 14, 7, 42, 42, 628628, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.CharField(default='', max_length=40),
        ),
    ]
