# Generated by Django 4.0.4 on 2022-06-14 08:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_contact_id_alter_product_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='adress',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='pincode',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 14, 8, 11, 46, 437047, tzinfo=utc)),
        ),
    ]
