# Generated by Django 4.0.4 on 2022-06-14 10:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_contact_textarea_alter_product_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='password',
        ),
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 14, 10, 42, 1, 637869, tzinfo=utc)),
        ),
    ]
