# Generated by Django 4.0.4 on 2022-06-23 19:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_product_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('jsonitems', models.CharField(default='', max_length=5000)),
                ('name', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', models.IntegerField(default='')),
                ('address', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=40)),
                ('city', models.CharField(default='', max_length=40)),
                ('zipcode', models.IntegerField(default='')),
            ],
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='id',
            new_name='query_id',
        ),
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 23, 19, 35, 40, 29878, tzinfo=utc)),
        ),
    ]
